# Generated by Django 2.2.6 on 2019-11-07 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorygame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('time_stamp', models.DateTimeField(verbose_name='time stamp')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorygame.UserLogAction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorygame.User')),
            ],
        ),
    ]
