# Generated by Django 2.2.6 on 2019-11-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorygame', '0002_userlog_userlogaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(verbose_name='time stamp')),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
