# Generated by Django 2.2.6 on 2019-11-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorygame', '0003_serverlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermemoryquestionhistory',
            name='question',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='MemoryQuestion',
        ),
    ]
