# Generated by Django 2.2.6 on 2019-11-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorygame', '0004_auto_20191106_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermemoryquestionhistory',
            name='time_stamp',
            field=models.DateTimeField(null=True),
        ),
    ]
