# Generated by Django 2.2.6 on 2019-11-09 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorygame', '0006_auto_20191109_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('time_stamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('OPENED', 'OPENED'), ('ANSWERED', 'ANSWERED'), ('EXPIRED', 'EXPIRED')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('OPENED', 'OPENED'), ('ANSWERED', 'ANSWERED'), ('EXPIRED', 'EXPIRED')], max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorygame.Question')),
            ],
        ),
    ]
