# Generated by Django 2.2.6 on 2019-11-09 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorygame', '0007_question_questionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlog',
            name='assigned_to_user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='memorygame.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('OPENED', 'OPENED'), ('EXPIRED', 'EXPIRED')], max_length=200),
        ),
        migrations.AlterField(
            model_name='questionlog',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'ASSIGNED_TO_USER'), ('ANSWERED', 'ANSWERED'), ('EXPIRED', 'EXPIRED')], max_length=200),
        ),
    ]
