# Generated by Django 2.2.6 on 2019-11-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorygame', '0009_auto_20191109_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('GENERAL', 'GENERAL'), ('MATH', 'MATH'), ('MEMORY', 'MEMORY'), ('GEOGRAPHY', 'GEOGRAPHY')], max_length=200)),
            ],
        ),
    ]
