# Generated by Django 2.2.6 on 2019-11-14 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorygame', '0010_fixedquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AssignedProgramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('IN_PROCESS', 'IN_PROCESS'), ('DONE', 'DONE')], max_length=200)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorygame.AssignedProgram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorygame.User')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedProgramUserProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorygame.AssignedProgramUser')),
                ('user_question_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorygame.UserMemoryQuestionHistory')),
            ],
        ),
        migrations.CreateModel(
            name='UserActiveProgramContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorygame.AssignedProgramUserProgress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorygame.User')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedProgramCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_questions', models.IntegerField()),
                ('category', models.CharField(choices=[('GENERAL', 'GENERAL'), ('MATH', 'MATH'), ('MEMORY', 'MEMORY'), ('GEOGRAPHY', 'GEOGRAPHY')], max_length=200)),
                ('assigned_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorygame.AssignedProgram')),
            ],
        ),
    ]
