# Generated by Django 2.2.6 on 2019-11-15 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorygame', '0011_assignedprogram_assignedprogramcategory_assignedprogramuser_assignedprogramuserprogress_useractivepr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractiveprogramcontext',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorygame.AssignedProgramUser'),
        ),
    ]
