# Generated by Django 2.2.6 on 2019-11-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorygame', '0012_auto_20191115_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedprogramcategory',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'GENERAL'), ('MATH', 'MATH'), ('TIME', 'TIME'), ('MEMORY', 'MEMORY'), ('GEOGRAPHY', 'GEOGRAPHY'), ('CANADIAN_PROVINCES', 'CANADIAN_PROVINCES'), ('PROVINCE_CITY', 'PROVINCE_CITY')], max_length=200),
        ),
        migrations.AlterField(
            model_name='fixedquestion',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'GENERAL'), ('MATH', 'MATH'), ('TIME', 'TIME'), ('MEMORY', 'MEMORY'), ('GEOGRAPHY', 'GEOGRAPHY'), ('CANADIAN_PROVINCES', 'CANADIAN_PROVINCES'), ('PROVINCE_CITY', 'PROVINCE_CITY')], max_length=200),
        ),
    ]
