# Generated by Django 2.2.6 on 2019-11-16 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorygame', '0013_auto_20191116_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermemoryquestionhistory',
            name='question_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='memorygame.QuestionLog'),
        ),
    ]
