# Generated by Django 2.2.6 on 2019-11-16 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorygame', '0014_usermemoryquestionhistory_question_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermemoryquestionhistory',
            name='program_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='memorygame.AssignedProgramUser'),
        ),
        migrations.DeleteModel(
            name='AssignedProgramUserProgress',
        ),
    ]
