# Generated by Django 2.2.6 on 2019-11-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorygame', '0015_auto_20191116_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('NO_CATEGORY', 'NO_CATEGORY'), ('GENERAL', 'GENERAL'), ('MATH', 'MATH'), ('TIME', 'TIME'), ('MEMORY', 'MEMORY'), ('GEOGRAPHY', 'GEOGRAPHY'), ('CANADIAN_PROVINCES', 'CANADIAN_PROVINCES'), ('PROVINCE_CITY', 'PROVINCE_CITY')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assignedprogramcategory',
            name='category',
            field=models.CharField(choices=[('NO_CATEGORY', 'NO_CATEGORY'), ('GENERAL', 'GENERAL'), ('MATH', 'MATH'), ('TIME', 'TIME'), ('MEMORY', 'MEMORY'), ('GEOGRAPHY', 'GEOGRAPHY'), ('CANADIAN_PROVINCES', 'CANADIAN_PROVINCES'), ('PROVINCE_CITY', 'PROVINCE_CITY')], max_length=200),
        ),
        migrations.AlterField(
            model_name='fixedquestion',
            name='category',
            field=models.CharField(choices=[('NO_CATEGORY', 'NO_CATEGORY'), ('GENERAL', 'GENERAL'), ('MATH', 'MATH'), ('TIME', 'TIME'), ('MEMORY', 'MEMORY'), ('GEOGRAPHY', 'GEOGRAPHY'), ('CANADIAN_PROVINCES', 'CANADIAN_PROVINCES'), ('PROVINCE_CITY', 'PROVINCE_CITY')], max_length=200),
        ),
    ]
