# Generated by Django 2.2.6 on 2019-11-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorygame', '0017_auto_20191120_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedprogramcategory',
            name='category',
            field=models.CharField(choices=[('NO_CATEGORY', 'NO_CATEGORY'), ('GENERAL', 'GENERAL'), ('MATH', 'MATH'), ('TIME', 'TIME'), ('DIVISION', 'DIVISION'), ('MULTIPLICATION', 'MULTIPLICATION'), ('ADDITION', 'ADDITION'), ('SUBTRACTION', 'SUBTRACTION'), ('MEMORY', 'MEMORY'), ('GEOGRAPHY', 'GEOGRAPHY'), ('CANADIAN_PROVINCES', 'CANADIAN_PROVINCES'), ('PROVINCE_CITY', 'PROVINCE_CITY')], max_length=200),
        ),
        migrations.AlterField(
            model_name='fixedquestion',
            name='category',
            field=models.CharField(choices=[('NO_CATEGORY', 'NO_CATEGORY'), ('GENERAL', 'GENERAL'), ('MATH', 'MATH'), ('TIME', 'TIME'), ('DIVISION', 'DIVISION'), ('MULTIPLICATION', 'MULTIPLICATION'), ('ADDITION', 'ADDITION'), ('SUBTRACTION', 'SUBTRACTION'), ('MEMORY', 'MEMORY'), ('GEOGRAPHY', 'GEOGRAPHY'), ('CANADIAN_PROVINCES', 'CANADIAN_PROVINCES'), ('PROVINCE_CITY', 'PROVINCE_CITY')], max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('NO_CATEGORY', 'NO_CATEGORY'), ('GENERAL', 'GENERAL'), ('MATH', 'MATH'), ('TIME', 'TIME'), ('DIVISION', 'DIVISION'), ('MULTIPLICATION', 'MULTIPLICATION'), ('ADDITION', 'ADDITION'), ('SUBTRACTION', 'SUBTRACTION'), ('MEMORY', 'MEMORY'), ('GEOGRAPHY', 'GEOGRAPHY'), ('CANADIAN_PROVINCES', 'CANADIAN_PROVINCES'), ('PROVINCE_CITY', 'PROVINCE_CITY')], max_length=200, null=True),
        ),
    ]
