package:
  name: ttpy
  version: "1.0"

source:
    #      fn: ttpy-1.0.tar
    #url: https://dl.dropboxusercontent.com/u/49234889/ttpy-1.0.tar
    #md5: ff081595d853c4c563dba96aa9180f1c
source:
    git_url: git://github.com/oseledets/ttpy
    git_branch: master
   #  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyinstrument = pyinstrument:main
    #
    # Would create an entry point called pyinstrument that calls pyinstrument.main()

    # - pyinstrument = pyinstrument.__main__:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - cython
      #    - accelerate

  run:
    - python
    - numpy
    - cython
      #    - accelerate

test:
  # Python imports
  imports:
    - numpy
    - tt

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    # - pyinstrument --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/oseledets/ttpy
  license: MIT License
  summary: u"Python implementation of the TT-Toolbox."

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
